export const ROUTER = {
  LOGIN: "/",
  REGISTER: "/register",
  VERIFY: "/verify",
  UPDATE_PASSWORD: "/update-password",
  FORGET_PASSWORD: "/forget-password",
  VERIFY_CODE: "/verify-code",
  NOT_FOUND: "*",
  ADMIN: "/admin",
  PRODUCTS: "products/",
  CATEGORIES: "categories/",
  STATISTICS: "statistics",
  STAFF: "staff/",
  ROLES: "roles",
  CREATE: "create",
  EDIT: "edit",
  SETTINGS: "settings",
  DETAIL: "detail",
  CREATE_FLOW: "create-flow",
  FLOW: "flow",
  PAYMENTS: "payments",
};
